"""0003_setting_cascade_delete_on_user_genre_table

Revision ID: 24e881b5dc0e
Revises: 0ca68c620f48
Create Date: 2021-02-09 20:13:05.684551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24e881b5dc0e'
down_revision = '0ca68c620f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_genre_genre_id_fkey', 'user_genre', type_='foreignkey')
    op.drop_constraint('user_genre_user_id_fkey', 'user_genre', type_='foreignkey')
    op.create_foreign_key(None, 'user_genre', 'User', ['user_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'user_genre', 'Genre', ['genre_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_genre', type_='foreignkey')
    op.drop_constraint(None, 'user_genre', type_='foreignkey')
    op.create_foreign_key('user_genre_user_id_fkey', 'user_genre', 'User', ['user_id'], ['id'])
    op.create_foreign_key('user_genre_genre_id_fkey', 'user_genre', 'Genre', ['genre_id'], ['id'])
    # ### end Alembic commands ###
