"""0009_update_shows_schema

Revision ID: 3cbcb23afaee
Revises: 98273cbdf7fd
Create Date: 2021-03-19 15:08:33.993230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cbcb23afaee'
down_revision = '98273cbdf7fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('aritist_name', sa.String(length=50), nullable=False))
    op.add_column('Show', sa.Column('artist_image_link', sa.String(length=500), nullable=True))
    op.add_column('Show', sa.Column('city', sa.String(length=20), nullable=False))
    op.add_column('Show', sa.Column('state', sa.String(length=20), nullable=False))
    op.add_column('Show', sa.Column('venue_name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'venue_name')
    op.drop_column('Show', 'state')
    op.drop_column('Show', 'city')
    op.drop_column('Show', 'artist_image_link')
    op.drop_column('Show', 'aritist_name')
    # ### end Alembic commands ###
