"""0004_setting_unique_constrain_in_Genres

Revision ID: e9f0fcc2fa9d
Revises: 24e881b5dc0e
Create Date: 2021-02-09 20:16:52.312030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9f0fcc2fa9d'
down_revision = '24e881b5dc0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Genre', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Genre', type_='unique')
    # ### end Alembic commands ###
