"""0010_fixing_typo_in_shows

Revision ID: 492c06179166
Revises: 3cbcb23afaee
Create Date: 2021-03-19 16:05:25.418500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '492c06179166'
down_revision = '3cbcb23afaee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('artist_name', sa.String(length=50), nullable=False))
    op.drop_column('Show', 'aritist_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('aritist_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('Show', 'artist_name')
    # ### end Alembic commands ###
