"""0008_adding_website_and_seeking_venues_in_models

Revision ID: 98273cbdf7fd
Revises: ea23104c71a3
Create Date: 2021-03-02 11:19:58.410585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98273cbdf7fd'
down_revision = 'ea23104c71a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=250), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
